### ISSUE TITLE
my helper class in swift

### ISSUE THREAD

**Issue by amorenew** [dimohamdy/iOS-Localize-Constrain#3]
//
   //  Localize.swift
   import Foundation

   /// Internal current language key
   let LCLCurrentLanguageKey = "LCLCurrentLanguageKey"
  /// Default language. English. If English is unavailable defaults to base localization.
let LCLDefaultLanguage = "en"

/// Name for language change notification
public let LCLLanguageChangeNotification = "LCLLanguageChangeNotification"

// MARK: Localization Syntax

/**
Swift 1.x friendly localization syntax, replaces NSLocalizedString
- Parameter string: Key to be localized.
- Returns: The localized string.
  _/
  /_public func Localized(string: String) -> String {
  if let path = NSBundle.mainBundle().pathForResource(Localize.currentLanguage(), ofType: "lproj"), bundle = NSBundle(path: path) {
      return bundle.localizedStringForKey(string, value: nil, table: nil)
  }
  return string
  }

/**
 Swift 1.x friendly localization syntax with format arguments, replaces String(format:NSLocalizedString)
- Parameter string: Key to be localized.
- Returns: The formatted localized string with arguments.
  */
  public func Localized(string: String, arguments args: CVarArgType...) -> String {
  return String(format: Localized(string), arguments: args)
  }

public extension String {
    /**
     Swift 2 friendly localization syntax, replaces NSLocalizedString
     - Returns: The localized string.
     _/
   /_ func localized() -> String {
        if let path = NSBundle.mainBundle().pathForResource(Localize.currentLanguage(), ofType: "lproj"), bundle = NSBundle(path: path) {
            return bundle.localizedStringForKey(self, value: nil, table: nil)
        }
        return self
    }*/

```
/**
 Swift 2 friendly localization syntax with format arguments, replaces String(format:NSLocalizedString)
 - Returns: The formatted localized string with arguments.
 */
/*func localizedWithFormat(arguments args: CVarArgType...) -> String {
    return String(format: localized(), arguments: args)
}*/
```

}
*/

class Localize {

```
class func getString(keyString : String)-> String {

   if let path = NSBundle.mainBundle().pathForResource(Localize.currentLanguage(), ofType: "lproj"), bundle = NSBundle(path: path) {
        return bundle.localizedStringForKey(keyString, value: nil, table: nil)
    }
    return NSLocalizedString(keyString, comment: "")

}
/**
 List available languages
 - Returns: Array of available languages.
 */
```

  class func availableLanguages() -> [String] {
        return NSBundle.mainBundle().localizations
    }

```
/**
 Current language
 - Returns: The current language. String.
 */
 class func currentLanguage() -> String {
    if let currentLanguage = NSUserDefaults.standardUserDefaults().objectForKey(LCLCurrentLanguageKey) as? String {
        return currentLanguage
    }
    return defaultLanguage()
}

/**
 Change the current language
 - Parameter language: Desired language.
 */
 class func setCurrentLanguage(language: String) {
    let selectedLanguage = availableLanguages().contains(language) ? language : defaultLanguage()
    if (selectedLanguage != currentLanguage()){
        NSUserDefaults.standardUserDefaults().setObject(selectedLanguage, forKey: LCLCurrentLanguageKey)
        NSUserDefaults.standardUserDefaults().synchronize()
        NSNotificationCenter.defaultCenter().postNotificationName(LCLLanguageChangeNotification, object: nil)
    }
}

/**
 Default language
 - Returns: The app's default language. String.
 */
class func defaultLanguage() -> String {
    var defaultLanguage: String = String()
    guard let preferredLanguage = NSBundle.mainBundle().preferredLocalizations.first else {
        return LCLDefaultLanguage
    }
    let availableLanguages: [String] = self.availableLanguages()
    if (availableLanguages.contains(preferredLanguage)) {
        defaultLanguage = preferredLanguage
    }
    else {
        defaultLanguage = LCLDefaultLanguage
    }
    return defaultLanguage
}

/**
 Resets the current language to the default
 */
class func resetCurrentLanguageToDefault() {
    setCurrentLanguage(self.defaultLanguage())
}

/**
 Get the current language's display name for a language.
 - Parameter language: Desired language.
 - Returns: The localized string.
 */
class func displayNameForLanguage(language: String) -> String {
    let locale : NSLocale = NSLocale(localeIdentifier: currentLanguage())
    if let displayName = locale.displayNameForKey(NSLocaleLanguageCode, value: language) {
        return displayName
    }
    return String()
}
class func changeViewToRTL(view:UIView,inout isRTL:Bool){
    if !isRTL {
      //Localize.setCurrentLanguage("ar")
            LocalizeViewToRTL(view)
        view.layoutIfNeeded()

    }
    isRTL = true
}
class func LocalizeViewToRTL(view:UIView){
        Localize.changeViewConstrainsToRTL(view)
       // Localize.changeViewLeftRightMarginToRTL(view)
        //Localize.changeViewLeftRightToRTL(view)
       // Localize.changeViewConstrainsTrailingLeadingMarginToRTL(view)

    Localize.localizeViewText(view)
    for subView in view.subviews {
        Localize.LocalizeViewToRTL(subView)
    }
   // view.setNeedsDisplay()
   // view.needsUpdateConstraints()
   // view.layoutIfNeeded()
}
```

   class func changeViewConstrainsToRTL (tempView:UIView) {
        for  constrain in tempView.constraints {
            var firstAttribute:NSLayoutAttribute = constrain.firstAttribute;
            var secondAttribute:NSLayoutAttribute = constrain.secondAttribute;
            if (firstAttribute == NSLayoutAttribute.Leading || firstAttribute == NSLayoutAttribute.Trailing) && (secondAttribute == NSLayoutAttribute.Leading || secondAttribute == NSLayoutAttribute.Trailing) {
                if (constrain.firstAttribute == NSLayoutAttribute.Leading) {
                    firstAttribute = NSLayoutAttribute.Trailing;
                } else if (constrain.firstAttribute == NSLayoutAttribute.Trailing) {
                    firstAttribute = NSLayoutAttribute.Leading;
                }
                if (constrain.secondAttribute == NSLayoutAttribute.Leading) {
                    secondAttribute = NSLayoutAttribute.Trailing;
                } else if (constrain.secondAttribute == NSLayoutAttribute.Trailing) {
                    secondAttribute = NSLayoutAttribute.Leading;
                }
               constrain.constant *= -1
                let constrainNew: NSLayoutConstraint = NSLayoutConstraint(item: constrain.firstItem, attribute: firstAttribute, relatedBy: constrain.relation, toItem: constrain.secondItem, attribute: secondAttribute, multiplier: constrain.multiplier, constant: constrain.constant)
                tempView.removeConstraint(constrain)
                tempView.addConstraint(constrainNew)
            }

```
    }
}
```

   /\* class func changeViewLeftRightToRTL (tempView:UIView) {
        for  constrain in tempView.constraints {
            var firstAttribute:NSLayoutAttribute = constrain.firstAttribute;
            var secondAttribute:NSLayoutAttribute = constrain.secondAttribute;
            //Swap Constrain Left And Right
            if (firstAttribute == NSLayoutAttribute.Left || firstAttribute == NSLayoutAttribute.Right) && (secondAttribute == NSLayoutAttribute.Left || secondAttribute == NSLayoutAttribute.Right) {
                if (constrain.firstAttribute == NSLayoutAttribute.Left) {
                    firstAttribute = NSLayoutAttribute.Right;
                } else if (constrain.firstAttribute == NSLayoutAttribute.Right) {
                    firstAttribute = NSLayoutAttribute.Left;
                }
                if (constrain.secondAttribute == NSLayoutAttribute.Left) {
                    secondAttribute = NSLayoutAttribute.Right;
                } else if (constrain.secondAttribute == NSLayoutAttribute.Right) {
                    secondAttribute = NSLayoutAttribute.Left;
                }
                constrain.constant _= -1
                let constrainNew: NSLayoutConstraint = NSLayoutConstraint(item: constrain.firstItem, attribute: firstAttribute, relatedBy: constrain.relation, toItem: constrain.secondItem, attribute: secondAttribute, multiplier: constrain.multiplier, constant: constrain.constant)
                tempView.removeConstraint(constrain)
                tempView.addConstraint(constrainNew)
            }
            //End Swap Constrain Left And Right
        }
    }_/

   /\* class func changeViewLeftRightMarginToRTL (tempView:UIView) {
       /\* case LeftMargin
        case RightMargin*/
        for  constrain in tempView.constraints {
            var firstAttribute:NSLayoutAttribute = constrain.firstAttribute;
            var secondAttribute:NSLayoutAttribute = constrain.secondAttribute;
            if (firstAttribute == NSLayoutAttribute.LeftMargin || firstAttribute == NSLayoutAttribute.RightMargin) && (secondAttribute == NSLayoutAttribute.LeftMargin || secondAttribute == NSLayoutAttribute.RightMargin) {
                if (constrain.firstAttribute == NSLayoutAttribute.LeftMargin) {
                    firstAttribute = NSLayoutAttribute.RightMargin;
                } else if (constrain.firstAttribute == NSLayoutAttribute.RightMargin) {
                    firstAttribute = NSLayoutAttribute.LeftMargin;
                }
                if (constrain.secondAttribute == NSLayoutAttribute.LeftMargin) {
                    secondAttribute = NSLayoutAttribute.RightMargin;
                } else if (constrain.secondAttribute == NSLayoutAttribute.RightMargin) {
                    secondAttribute = NSLayoutAttribute.LeftMargin;
                }
                constrain.constant *= -1
                let constrainNew: NSLayoutConstraint = NSLayoutConstraint(item: constrain.firstItem, attribute: firstAttribute, relatedBy: constrain.relation, toItem: constrain.secondItem, attribute: secondAttribute, multiplier: constrain.multiplier, constant: constrain.constant)
                tempView.removeConstraint(constrain)
                tempView.addConstraint(constrainNew)
            }

```
    }
}*/
```

   /\* class func changeViewConstrainsTrailingLeadingMarginToRTL (tempView:UIView) {
        for  constrain in tempView.constraints {
            var firstAttribute:NSLayoutAttribute = constrain.firstAttribute;
            var secondAttribute:NSLayoutAttribute = constrain.secondAttribute;
            if (firstAttribute == NSLayoutAttribute.LeadingMargin || firstAttribute == NSLayoutAttribute.TrailingMargin) && (secondAttribute == NSLayoutAttribute.LeadingMargin || secondAttribute == NSLayoutAttribute.TrailingMargin) {
                if (constrain.firstAttribute == NSLayoutAttribute.LeadingMargin) {
                    firstAttribute = NSLayoutAttribute.TrailingMargin;
                } else if (constrain.firstAttribute == NSLayoutAttribute.TrailingMargin) {
                    firstAttribute = NSLayoutAttribute.LeadingMargin;
                }
                if (constrain.secondAttribute == NSLayoutAttribute.LeadingMargin) {
                    secondAttribute = NSLayoutAttribute.TrailingMargin;
                } else if (constrain.secondAttribute == NSLayoutAttribute.TrailingMargin) {
                    secondAttribute = NSLayoutAttribute.LeadingMargin;
                }
                constrain.constant *= -1
                let constrainNew: NSLayoutConstraint = NSLayoutConstraint(item: constrain.firstItem, attribute: firstAttribute, relatedBy: constrain.relation, toItem: constrain.secondItem, attribute: secondAttribute, multiplier: constrain.multiplier, constant: constrain.constant)
                tempView.removeConstraint(constrain)
                tempView.addConstraint(constrainNew)
            }

```
    }
}*/
```

   class func localizeViewText(view:UIView){
        if view.isKindOfClass(UIButton){
            if let label:UILabel = (view as! UIButton).titleLabel{
                if let _:String = label.text{
                label.text = Localize.getString(label.localizedText)
                    if  label.textAlignment == .Left {
                        label.textAlignment = .Right
                    }else{
                        label.textAlignment = .Left
                    }
                }
            }
        }else if view.isKindOfClass( UITextField){
            if let _:String = (view as! UITextField).text{
                (view as! UITextField).text = Localize.getString((view as! UITextField).localizedText)
                if  (view as! UITextField).textAlignment == .Left {
                    (view as! UITextField).textAlignment = .Right
                }else{
                    (view as! UITextField).textAlignment = .Left
                }
            }
        }else if view.isKindOfClass(UILabel){
             (view as! UILabel)

```
        if let _:String = (view as! UILabel).text{
            (view as! UILabel).text = Localize.getString((view as! UILabel).localizedText)
            if  (view as! UILabel).textAlignment == .Left {
                (view as! UILabel).textAlignment = .Right
            }else{
                (view as! UILabel).textAlignment = .Left
            }
        }
    }
}
```

}

**Comment by amorenew** [comment]
import Foundation

extension UILabel {

```
var localizedText: String {
    set (key) {
        text = Localize.getString(key)
    }
    get {
        return text!
    }
}
```

}
extension UITextField {

```
var localizedText: String {
    set (key) {
        text = Localize.getString(key)
    }
    get {
        return text!
    }
}
```

}
extension UIButton {
    var localizedTitleForNormal: String {
        set (key) {
            setTitle(Localize.getString(key), forState: .Normal)
        }
        get {
            return titleForState(.Normal)!
        }
    }

```
var localizedTitleForHighlighted: String {
    set (key) {
        setTitle(Localize.getString(key), forState: .Highlighted)
    }
    get {
        return titleForState(.Highlighted)!
    }
}
```

}

**Comment by amorenew** [comment]
in custom table view cell class

 var isRTL = false
    func localizeView() {
        Localize.changeViewToRTL(self, isRTL: &isRTL)
    }
    override func layoutSubviews() {
        super.layoutSubviews()
        localizeView()

```
}
override func prepareForReuse() {
    self.localizeView()
}
```

**Comment by amorenew** [comment]
my problem is custom table cell not work well after renter it's view controller

**Comment by dimohamdy** [comment]
@amorenew  for cell you can use  tableView:willDisplayCell:forRowAtIndexPath Delegate

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITableViewDelegate_Protocol/#//apple_ref/occ/intfm/UITableViewDelegate/tableView:willDisplayCell:forRowAtIndexPath:

**Comment by amorenew** [comment]
i tried it but it make bad performance

**Comment by dimohamdy** [comment]
@amorenew  this library in swift 
https://github.com/dimohamdy/Swift-iOS-Localize-Constraint

**Comment by dimohamdy** [comment]
@amorenew  you can add tag to cell that converted to RTL and other cell convert it

**Comment by amorenew** [comment]
i will check it 
this all to support io8
in ios 9 you can force rtl in runtime

**Comment by dimohamdy** [comment]
i know this After alot of time apple make this :smile:
